### ISSUE TITLE
Test on Microbit V2

### ISSUE THREAD

**Issue by ryanteck** [PiSupply/pxt-tinker-kit#1]

**Comment by ryanteck** [comment]
I don't have this kit at all yet so to test would need one @shawaj however currently I can roughly guestimate what will work.

In this one theres:

- OLED - Not sure on current status.
- Servo - Believed working.
- PIR - I believe this is just a digital input so should work.
- Soil Moisture - Analog value so should work.
- ADKeypad  - I'm going to guess this keypad works by changing resistance to know which button is pressed so analog.
- Crash Sensor - Digital input so should work.
- Buzzer - Digital output so should work. However possibly not at the same time as the V2s speaker.
- Red LED - Digital output so should work.
- Green LED - Digital output so should work.
- Blue LED - Digital output so should work.
- Analog - Analog value so should work.

The main one would be checking the OLED, and then the servo from the Bit Buggy as the rest are basic components.

**Comment by ryanteck** [comment]
Ok so thanks to getting the Bit Buggy I've been able to test bits that cross over.

Neopixels are now working, digital outputs all working, servos work too.

Only thing I haven't tested is the OLED screen.

**Comment by shawaj** [comment]
@ryanteck nice one thanks

**Comment by shawaj** [comment]
Do you want us to send a tinker kit and starter kit @ryanteck ?

**Comment by ryanteck** [comment]
That's up to you with the tinker kit @shawaj , i think the only thing I can't test without one is the OLED.

I think I might already have a starter kit, but a quick look over and it doesn't look like it contains anything different to try out so no need for that one at all.

**Comment by shawaj** [comment]
@ryanteck sure will send

**Comment by ryanteck** [comment]
@shawaj OLED is all working and the other sensors I'm happy with so all working
